In [1]:
import numpy as np
import pandas as pd

In [7]:
df = pd.read_excel("Forecast_Comparison_INTRADAY_01-08-2024.xlsx")
df

,Block Number,R1,R2,R3,R4,R5,R6,R7,R8,R9,...,R39,R40,R41,R42,R43,R44,R45,R46,R47,R48
0,1,15710.93,15710.93,15710.93,15710.93,15710.93,15710.93,15710.93,15710.93,15710.93,...,15710.93,15710.93,15710.93,15710.93,15710.93,15710.93,15710.93,15710.93,15710.93,15710.93
1,2,15688.31,15688.31,15688.31,15688.31,15688.31,15688.31,15688.31,15688.31,15688.31,...,15688.31,15688.31,15688.31,15688.31,15688.31,15688.31,15688.31,15688.31,15688.31,15688.31
2,3,15617.92,15517.92,15517.92,15517.92,15517.92,15517.92,15517.92,15517.92,15517.92,...,15517.92,15517.92,15517.92,15517.92,15517.92,15517.92,15517.92,15517.92,15517.92,15517.92
3,4,15552.37,15452.37,15452.37,15452.37,15452.37,15452.37,15452.37,15452.37,15452.37,...,15452.37,15452.37,15452.37,15452.37,15452.37,15452.37,15452.37,15452.37,15452.37,15452.37
4,5,15460.30,15360.30,14964.87,14964.87,14964.87,14964.87,14964.87,14964.87,14964.87,...,14964.87,14964.87,14964.87,14964.87,14964.87,14964.87,14964.87,14964.87,14964.87,14964.87
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
91,92,16044.04,16044.04,16044.04,16044.04,16044.04,16044.04,16044.04,16044.04,16044.04,...,15696.13,15691.23,15453.85,15453.85,15654.47,15816.54,15784.20,15784.20,15691.23,15691.23
92,93,15914.75,15914.75,15914.75,15914.75,15914.75,15914.75,15914.75,15914.75,15914.75,...,15585.55,15580.70,15345.23,15345.23,15544.23,15705.00,15672.92,15672.92,15686.61,15580.70
93,94,15759.76,15759.76,15759.76,15759.76,15759.76,15759.76,15759.76,15759.76,15759.76,...,15449.53,15444.72,15211.55,15211.55,15408.61,15567.81,15536.05,15536.05,15648.62,15444.72
94,95,15614.44,15614.44,15614.44,15614.44,15614.44,15614.44,15614.44,15614.44,15614.44,...,15322.68,15317.92,15086.90,15086.90,15282.14,15439.88,15408.40,15408.40,15519.94,15404.83
95,96,15535.60,15535.60,15535.60,15535.60,15535.60,15535.60,15535.60,15535.60,15535.60,...,15260.85,15256.12,15026.26,15026.26,15220.52,15377.45,15346.14,15346.14,15457.12,15342.59

In [9]:
df2 = df.copy()
df2.set_index(['Block Number'], inplace=True)
df2.head()

,R1,R2,R3,R4,R5,R6,R7,R8,R9,R10,...,R39,R40,R41,R42,R43,R44,R45,R46,R47,R48
Block Number,,,,,,,,,,,,,,,,,,,,,
1,15710.93,15710.93,15710.93,15710.93,15710.93,15710.93,15710.93,15710.93,15710.93,15710.93,...,15710.93,15710.93,15710.93,15710.93,15710.93,15710.93,15710.93,15710.93,15710.93,15710.93
2,15688.31,15688.31,15688.31,15688.31,15688.31,15688.31,15688.31,15688.31,15688.31,15688.31,...,15688.31,15688.31,15688.31,15688.31,15688.31,15688.31,15688.31,15688.31,15688.31,15688.31
3,15617.92,15517.92,15517.92,15517.92,15517.92,15517.92,15517.92,15517.92,15517.92,15517.92,...,15517.92,15517.92,15517.92,15517.92,15517.92,15517.92,15517.92,15517.92,15517.92,15517.92
4,15552.37,15452.37,15452.37,15452.37,15452.37,15452.37,15452.37,15452.37,15452.37,15452.37,...,15452.37,15452.37,15452.37,15452.37,15452.37,15452.37,15452.37,15452.37,15452.37,15452.37
5,15460.30,15360.30,14964.87,14964.87,14964.87,14964.87,14964.87,14964.87,14964.87,14964.87,...,14964.87,14964.87,14964.87,14964.87,14964.87,14964.87,14964.87,14964.87,14964.87,14964.87

In [18]:
for i in range(0, 47):
    df2.iloc[:2*(i+1), i] = df.loc[:2*(i+1)-1, 'R48']

df2

,R1,R2,R3,R4,R5,R6,R7,R8,R9,R10,...,R39,R40,R41,R42,R43,R44,R45,R46,R47,R48
Block Number,,,,,,,,,,,,,,,,,,,,,
1,15710.93,15710.93,15710.93,15710.93,15710.93,15710.93,15710.93,15710.93,15710.93,15710.93,...,15710.93,15710.93,15710.93,15710.93,15710.93,15710.93,15710.93,15710.93,15710.93,15710.93
2,15688.31,15688.31,15688.31,15688.31,15688.31,15688.31,15688.31,15688.31,15688.31,15688.31,...,15688.31,15688.31,15688.31,15688.31,15688.31,15688.31,15688.31,15688.31,15688.31,15688.31
3,15617.92,15517.92,15517.92,15517.92,15517.92,15517.92,15517.92,15517.92,15517.92,15517.92,...,15517.92,15517.92,15517.92,15517.92,15517.92,15517.92,15517.92,15517.92,15517.92,15517.92
4,15552.37,15452.37,15452.37,15452.37,15452.37,15452.37,15452.37,15452.37,15452.37,15452.37,...,15452.37,15452.37,15452.37,15452.37,15452.37,15452.37,15452.37,15452.37,15452.37,15452.37
5,15460.30,15360.30,14964.87,14964.87,14964.87,14964.87,14964.87,14964.87,14964.87,14964.87,...,14964.87,14964.87,14964.87,14964.87,14964.87,14964.87,14964.87,14964.87,14964.87,14964.87
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
92,16044.04,16044.04,16044.04,16044.04,16044.04,16044.04,16044.04,16044.04,16044.04,16044.04,...,15696.13,15691.23,15453.85,15453.85,15654.47,15816.54,15784.20,15691.23,15691.23,15691.23
93,15914.75,15914.75,15914.75,15914.75,15914.75,15914.75,15914.75,15914.75,15914.75,15914.75,...,15585.55,15580.70,15345.23,15345.23,15544.23,15705.00,15672.92,15672.92,15580.70,15580.70
94,15759.76,15759.76,15759.76,15759.76,15759.76,15759.76,15759.76,15759.76,15759.76,15759.76,...,15449.53,15444.72,15211.55,15211.55,15408.61,15567.81,15536.05,15536.05,15444.72,15444.72
95,15614.44,15614.44,15614.44,15614.44,15614.44,15614.44,15614.44,15614.44,15614.44,15614.44,...,15322.68,15317.92,15086.90,15086.90,15282.14,15439.88,15408.40,15408.40,15519.94,15404.83
96,15535.60,15535.60,15535.60,15535.60,15535.60,15535.60,15535.60,15535.60,15535.60,15535.60,...,15260.85,15256.12,15026.26,15026.26,15220.52,15377.45,15346.14,15346.14,15457.12,15342.59

In [20]:
df2.to_csv("new.csv", index=True)